
@endpoint=http://localhost:4001/api/v1
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmQ3MDZkNjA5MjQxODczYWU0MTk1ZmEiLCJ1c2VybmFtZSI6IlRlc3QgVXNlciIsImlhdCI6MTY1OTQ0OTU2MSwiZXhwIjoxNjU5NTM1OTYxfQ.20opSUgx7bXYDzvsJ9yF6CPJ3h0G4amYeMez10MdzkA
### RENTALS
### getRentals with req.query
GET {{endpoint}}/rentals?city=new%20york

### getRentals
GET {{endpoint}}/rentals


### getUserRentals 
GET {{endpoint}}/rentals/me
Content-Type: application/json
Authorization: Bearer {{token}}

### getRental
GET {{endpoint}}/rentals/62d54eabd5175ab4871a11


### createRental
POST {{endpoint}}/rentals
Content-Type: application/json

{
  "title": "Modern apartment in center 333",
  "city": "Madrid",
  "street": "calle falsa 123",
  "category": "apartmento",
  "image": "https://booksync-jerga-prod.s3.amazonaws.com/uploads/rental/image/5/image.jpeg",
  "numOfRooms": 3,
  "description": "Very nice apartment in center of the city.",
  "dailyPrice": 11,
  "owner": "62d706d609241873ae4195fb",
  "shared": false, 
  "createdAt": "2021-05-06"
}

### updateRental
PUT {{endpoint}}/rentals/62d480e246cf894816668ffe
Content-Type: application/json

{
  "title": "Depertamento moderno en el centro",
  "city": "Madrid",
  "street": "calle falsa 123",
  "category": "departamento",
  "image": "https://booksync-jerga-prod.s3.amazonaws.com/uploads/rental/image/5/image.jpeg",
  "numOfRooms": 1,
  "description": "Very nice apartment in center of the city.",
  "dailyPrice": 13,
  "shared": true, 
  "createdAt": "2021-06-06"
}

### deleteRental
DELETE {{endpoint}}/rentals/62d54ae6dbdf2d3a3d5e4fb7

### USERS ROUTES

### users/login
POST {{endpoint}}/users/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "testtest"
}

### users/register
POST {{endpoint}}/users/register
Content-Type: application/json

{
  "username": "Matias",
  "email": "matias@gmail.com",
  "password": "123456",
  "passwordConfirmation": "123456"
}

### secret protected route
GET {{endpoint}}/secret
Authorization: Bearer {{token}}

### BOOKINGS

### getBookings query
GET {{endpoint}}/bookings?startAt=2021-05-05&endAt=2021-05-12

### getBookings
GET {{endpoint}}/bookings


### getUserBookings
GET {{endpoint}}/bookings/me
Content-Type: application/json
Authorization: Bearer {{token}}


### CREATE booking endpoint
POST {{endpoint}}/bookings
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "startAt": 2022-07-01,
  "endAt": 2021-07-06,
  "price": 900,
  "nights": 3,
  "guests": 2,
  "user": { "$oid": "62d706d609241873ae4195fb" },
  "rental": { "$oid": "62d706d609241873ae4195f4" }
}

### getRecievedBookings
GET {{endpoint}}/bookings/recieved
Content-Type: application/json
Authorization: Bearer {{token}}


### deleteBooking
DELETE {{endpoint}}/bookings/62dd5a7844606700c85560c8
Content-Type: application/json
Authorization: Bearer {{token}}

### IMAGE-UPLOAD ROUTES
POST {{endpoint}}/image-upload
Content-Type: application/json
Authorization: Bearer {{token}}

### response example
# {
#   "_id": "62e94c9bb17dc5698b5ee4fb",
#   "url": "https://res.cloudinary.com/dggqfqhaf/image/upload/v1659456667/hsdh435yylfrdmleauvc.png"
# }