
@endpoint=http://localhost:4001/api/v1
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmQ2YTM2MjFhNGU2MDE2MWU2Zjc4NmEiLCJ1c2VybmFtZSI6IlRlc3QgVXNlciIsImlhdCI6MTY1ODIzNTM1OSwiZXhwIjoxNjU4MzIxNzU5fQ.S8CBBG5tcZfvYMp_xu8xHl21sxoUrP6AWe81qQvfEDU



###
GET {{endpoint}}/rentals


###
GET {{endpoint}}/rentals/62d54eabd5175ab4871a11

###
POST {{endpoint}}/rentals
Content-Type: application/json

{
  "title": "Modern apartment in center 333",
  "city": "Madrid",
  "street": "calle falsa 123",
  "category": "apartmento",
  "image": "https://booksync-jerga-prod.s3.amazonaws.com/uploads/rental/image/5/image.jpeg",
  "numOfRooms": 3,
  "description": "Very nice apartment in center of the city.",
  "dailyPrice": 11,
  "shared": false, 
  "createdAt": "2021-05-06"
}

###
PUT {{endpoint}}/rentals/62d480e246cf894816668ffe
Content-Type: application/json

{
  "title": "Depertamento moderno en el centro",
  "city": "Madrid",
  "street": "calle falsa 123",
  "category": "departamento",
  "image": "https://booksync-jerga-prod.s3.amazonaws.com/uploads/rental/image/5/image.jpeg",
  "numOfRooms": 1,
  "description": "Very nice apartment in center of the city.",
  "dailyPrice": 13,
  "shared": true, 
  "createdAt": "2021-06-06"
}

###
DELETE {{endpoint}}/rentals/62d54ae6dbdf2d3a3d5e4fb7

### USERS ROUTES

POST {{endpoint}}/users/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "testtest"
}

# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MmQ1YWNjYmE3MjQ0NzhkMDk1YTNmMWIiLCJ1c2VybmFtZSI6Ik1hdGlhcyIsImlhdCI6MTY1ODE3MTg0MiwiZXhwIjoxNjU4MjU4MjQyfQ.BLNpiEqlkGmqwV4eJ6MbcMM94qGxYYzVr3oVnfpdiHM"
# }

###
POST {{endpoint}}/users/register
Content-Type: application/json

{
  "username": "Matias",
  "email": "matias@gmail.com",
  "password": "123456",
  "passwordConfirmation": "123456"
}

### secret protected route
GET {{endpoint}}/secret
Authorization: Bearer {{token}}